module.exports =
{
  TOKEN_ADDRESS:0,
  USER_ADDRESS:1,
  SIGNER_ADDRESS: 2,
  RECIPIENT_ADDRESS:3,
  CLOSING_ADDRESS:4,
  TIMEOUT:5,
  AMOUNT_OWED:6,
  OPENED_BLOCK:7,
  CLOSED_BLOCK:8,
  CLOSED_NONCE:9
}
