module.exports =
{
  TOKEN_ADDRESS:0 ,
  USER_ADDRESS:1,
  RECIPIENT_ADDRESS:2,
  CLOSING_ADDRESS:3,
  TIMEOUT:4,
  TOKEN_BALANCE:5,
  AMOUNT_OWED:6,
  OPENED_BLOCK:7,
  CLOSED_BLOCK:8,
  CLOSED_NONCE:9
}
